[theme.dark]
# Primary accent color for interactive elements in dark mode.
primaryColor = "#a2a2a2"  # Adjusted for dark mode

# Background color for the main content area in dark mode.
backgroundColor = "#121212"  # Adjusted for dark mode

# Background color used for the sidebar and most interactive widgets in dark mode.
secondaryBackgroundColor = "#2a2a2a"  # Adjusted for dark mode

# Color used for almost all text in dark mode.
textColor = "#ffffff"  # Adjusted for dark mode
