[theme]
primaryColor = "#e27a4a"  # Warm orange for better readability

# Background color for the main content area.
backgroundColor = "#ffe6cc"  # Warm light peach for a comfortable background

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#ffcc99"  # Soft warm peach for a pleasant sidebar experience

# Color used for almost all text.
textColor = "#000000"  # Black for clear and comfortable reading
