# Primary accent color for interactive elements.
primaryColor = "#4a90e2"  # Cool blue for better readability

# Background color for the main content area.
backgroundColor = "#e6f7ff"  # Light blue for a cooler background

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#b3cde3"  # Soft blue for a pleasant sidebar experience

# Color used for almost all text.
textColor = "#2c3e50"  # Dark blue for clear and comfortable reading

